***Numpy Tutorial from Scratch :→ Basic to Advanced 😎💯***

**So, we'll basically Start with a basic introduction and ends up with creating and plotting random data sets, and working with NumPy functions.** 

**We will learn :→**
*   Numpy Basic
*   NumPy Random
*   NumPy ufunc (Universal Functions)

***► What is NumPy❓***
*  NumPy stands for "Numerical Python" and is core Python library for numeric and scientific computing.
*  NumPy is a Python library used for working with arrays.
*  It also has functions for working in domain of linear algebra, fourier transform, and matrices
*  It consist of multi-dimensional array objects and collection of routines for processing these arrays.

***► Why Use NumPy❓***
*   In Python we have lists that serve the purpose of arrays, but they are slow to process.
*   NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
*   The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
*   Arrays are very frequently used in data science, where speed and resources are very important.

***► Why is NumPy Faster Than Lists ❓***
*   NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
*   This behavior is called locality of reference in computer science.
*   This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

***► NumPy – A Replacement for MatLab***
*   NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library).
*   This combination is widely used as a replacement for MatLab, a popular platform for technical computing.


In [ ]:
#import NumPy Library
import numpy
arr = numpy.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


In [ ]:
import numpy as np
arr = np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


In [ ]:
#checking version of numpy
print(np.__version__)

1.21.6


***► NumPy Creating Arrays***

*Create a NumPy ndarray Object*

*   NumPy is used to work with arrays. The array object in NumPy is called ndarray
*   To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.



**Example :→ Numpy array using Tuple**

In [ ]:
import numpy as np
arr = np.array((10,20,30,40,50))
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


***► Dimensions in Arrays***
*   0-D Arrays
*   1-D Arrays
*   2-D Arrays
*   3-D arrays



**→ 0-D Arrays**

In [ ]:
import numpy as np
arr = np.array(11)
print(arr)
print(type(arr))

11
<class 'numpy.ndarray'>


**→ 1-D Arrays**

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


**→ 2-D Arrays**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


**→ 3-D arrays**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [60 70 80 90]]]


***► Check Number of Dimensions❓***

*using **ndim** attribute*

In [ ]:
import numpy as np

n1 = np.array(11)
n2 = np.array([10,20,30,40])
n3 = np.array([[1,2,3,4],[5,6,7,8]])
n4 = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

print("n1 is ",n1.ndim,"-D Array")
print("n2 is ",n2.ndim,"-D Array")
print("n3 is ",n3.ndim,"-D Array")
print("n4 is ",n4.ndim,"-D Array")

n1 is  0 -D Array
n2 is  1 -D Array
n3 is  2 -D Array
n4 is  3 -D Array


***► Higher Dimensional Arrays***

*An array can have any number of dimensions.*

By using **ndmin** Attribute

In [ ]:
import numpy as np
n2 = np.array([10,20,30,40], ndmin=6)
print(n2)
print("Dimension of n2 is :", n2.ndim)

[[[[[[10 20 30 40]]]]]]
Dimension of n2 is : 6


***► NumPy Array Indexing***

*Access Array Elements*
*   Array indexing is the same as accessing an array element.
*   We can access an array element by referring to its index number.
*   The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.



**Example → **

In [ ]:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,1245,9999,896885])

#Get the first element from the  array
print(arr[0])

#Get the second element from the  array
print(arr[1])

#Get the last element from the  array
print(arr[-1])

#Get the 4th element & 6th element from the array and add them
print(arr[3] + arr[5])

10
11
896885
88


***► Access 2-D Array***

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("third element of first row :",arr[0,2])

print("third element of 2nd row :",arr[1,2])

print("4th element of first row & 2nd element of 2nd row and add them :",arr[0,3] + arr[1,1])

[[1 2 3 4]
 [5 6 7 8]]
third element of first row : 3
third element of 2nd row : 7
4th element of first row & 2nd element of 2nd row and add them : 10


***► Access 3-D Array***

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])
print(arr)
print(arr[0,0,0])
print(arr[0,1,3])
print(arr[1,0,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [60 70 80 90]]]
1
8
30


***► NumPy Array Slicing***

**→Slicing arrays**
* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].
* If we don't pass start its considered 0
* If we don't pass end its considered length of array in that dimension
* If we don't pass step its considered 1



**→ Example 1:**

In [ ]:
#Slice elements from index 1 to index 3 from the following array:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])
print(arr[1:3])

[11 22]


**Note:** The result includes the start index, but excludes the end index.

**→ Example 2:**

In [ ]:
#Slice elements from index 6 to the end of the array:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[6:])

[66  7  8  9 12 45 99 89 68 85]


**→ Example 3:**

In [ ]:
#Slice elements from the beginning to index 8 (not included):
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[:8])

[10 11 22 33 44 55 66  7]


**► Negative Slicing**

In [ ]:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[-6:-1])
print(arr[-13:-6])

[12 45 99 89 68]
[33 44 55 66  7  8  9]


**► Slicing 2-D Array**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[0,1:3])
print(arr[0, 1:4])
print(arr[0, 2:8])

print(arr[1, 0:4])

[2 3]
[2 3 4]
[3 4]
[5 6 7 8]


***► Both Slicing***

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[0:2 ,1])
print(arr[0:2, 3])

print(arr[0:2 , 1:3 ])

[2 6]
[4 8]
[[2 3]
 [6 7]]


***► Step Slicing***

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])

print(arr[1:6:2])
print(arr[1:8:3])
print(arr[::3])

[2 4 6]
[2 5 8]
[1 4 7]


***► NumPy Data Types***

**Data Types in Python**
*   strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
*  integer - used to represent integer numbers. e.g. -1, -2, -3,4,5
*  float - used to represent real numbers. e.g. 1.2, 42.42
*  boolean - used to represent True or False.
*  complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

**Data Types in NumPy**
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

**► Checking the Data Type of an Array**

using **dtype** 

**→ Example 1**

In [ ]:
import numpy as np
arr = np.array([1, 2, -3, 4])
print(arr.dtype)

int64


**→ Example 2**

In [ ]:
import numpy as np
arr = np.array(['YouTube','Simplifiedlearner','Google' , 'Apple'])
print(arr.dtype)

<U17


**► Converting Data Type on Existing Arrays**

using **astype()**

In [ ]:
import numpy as np
arr = np.array([1.1,2.6,9.89,5.76])
print(arr.dtype)

n1 = arr.astype("i")
print("The new array is :", n1)
print(n1.dtype)

float64
The new array is : [1 2 9 5]
int32


***► NumPy Array Copy vs View***
*   The Difference Between Copy and View : The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
*   The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
*  The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

**→ COPY: Examples**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

n1 = arr.copy()

arr[2] = 50

n1[0] = 89

print("Original Data:", arr)
print("Copied Data:", n1)

Original Data: [ 1  2 50  4  5  6]
Copied Data: [89  2  3  4  5  6]


***→ VIEW: Example***

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

n1 = arr.view()

arr[0] = 22
n1[-1] = 8

print("Original Data:", arr)
print("Viewed Data:", n1)

Original Data: [22  2  3  4  5  8]
Viewed Data: [22  2  3  4  5  8]


***► Numpy Array Shapes***

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print("Dimension of array is :", arr.ndim)
print("Shape of this array is :", arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Dimension of array is : 2
Shape of this array is : (2, 4)


***► NumPy Array Reshaping***

*→ Reshape From 1-D to 2-D*

In [ ]:
import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])
print("Dimension of Original Array:",arr.ndim)

n1 = arr.reshape(3,4)

print("Original Array:", arr)
print("Reshaped Array:→")
print(n1)
print("Dimension of Reshaped Array:",n1.ndim)


Dimension of Original Array: 1
Original Array: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Reshaped Array:→
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
Dimension of Reshaped Array: 2


*→ Reshape From 1-D to 3-D*

In [ ]:
import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

n1 = arr.reshape(2,3,2)

print("Original Array:", arr)
print("Dimension of Original Array:",arr.ndim)

print("Reshaped Array:→")
print(n1)
print("Dimension of Reshaped Array:",n1.ndim)

Original Array: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Dimension of Original Array: 1
Reshaped Array:→
[[[ 5 10]
  [15 20]
  [25 30]]

 [[35 40]
  [45 50]
  [55 60]]]
Dimension of Reshaped Array: 3


***► NumPy Array Iterating***

Iterating means going through elements one by one.

**→ Example 1**
*   Iterate 1-D array

In [ ]:
import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

for x in arr:
  print(x)

5
10
15
20
25
30
35
40
45
50
55
60


**→ Example 2**
*   Iterate 2-D array

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  print(x)

[1 2 3 4]
[5 6 7 8]


**→ Example 3**
*   Iterate 2-D array in scalar manner

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8


**→ Example 4**
* Iterate 3-D array

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in arr:
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[10 20 30 40]
 [60 70 80 90]]


**→ Example 5** **bold text**
* Iterate 3-D array in scalar manner

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
10
20
30
40
60
70
80
90


**→Iterating Arrays Using nditer()**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
10
20
30
40
60
70
80
90


**► Iterating With Different Step Size**

In [ ]:
import numpy as np
#arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in np.nditer(arr[:, ::3]):
  print(x)

1
2
3
4
10
20
30
40


***► Enumerated Iteration Using ndenumerate()***



In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

for x,y in np.ndenumerate(arr):
  print(x,y)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


***► NumPy Joining Array***
* Joining means putting contents of two or more arrays in a single array.
* In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

In [ ]:
#Join two arays
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.concatenate((n2,n1))
print(arr)

[ 2  4  6  8  5 10 15 20]


In [ ]:
#Join two 2-D array
import numpy as np

n1 = np.array([[1,2],[3,4]])
n2 = np.array([[6,7],[8,9]])

arr = np.concatenate((n1,n2))

print(arr)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [ ]:
#Join two 2-D arrays along rows (axis=1):
import numpy as np

n1 = np.array([[1,2],[3,4]])
n2 = np.array([[6,7],[8,9]])

arr = np.concatenate((n1,n2), axis=1)

print(arr)

[[1 2 6 7]
 [3 4 8 9]]


***► Joining Arrays Using Stack Functions***

In [ ]:
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.stack((n1,n2), axis=1)

print(arr)

[[ 5  2]
 [10  4]
 [15  6]
 [20  8]]


In [ ]:
#Stacking Along Rows →hstack
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.hstack((n1,n2))

print(arr)

[ 5 10 15 20  2  4  6  8]


In [ ]:
#Stacking Along Columns → vstack
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.vstack((n1,n2))

print(arr)

[[ 5 10 15 20]
 [ 2  4  6  8]]


In [ ]:
#Stacking Along Height (depth) → dstack
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.dstack((n1,n2))

print(arr)

[[[ 5  2]
  [10  4]
  [15  6]
  [20  8]]]


***► NumPy Searching Arrays***

return the indexes that get a match.

In [ ]:
#Example 1
import numpy as np
n1 = np.array([5,10,15,5,5,20,5,2])

arr = np.where(n1 == 5)
print(arr) #this will return index of all the 5

(array([0, 3, 4, 6]),)


In [ ]:
#Example 2
import numpy as np

n1 = np.array([[1,2,1,5,1],[1,5,1,3,4]])

arr = np.where(n1 == 1)
print(arr) 


(array([0, 0, 0, 1, 1]), array([0, 2, 4, 0, 2]))


In [ ]:
#Example 3
import numpy as np
n1 = np.array([5,10,15,5,24,20,5,2])

arr = np.where(n1%2 == 0)
print(arr) #returns index of all even number

(array([1, 4, 5, 7]),)


***► Search Sorted***

In [ ]:
import numpy as np
arr = np.array([2, 5, 6, 7, 8, 9])

n1 = np.searchsorted(arr, 5)
print(n1)

1


In [ ]:
#Find the indexes where the values 3, 5, and 7 should be inserted:
import numpy as np
arr = np.array([1,2,4,6,8,9])

n1 = np.searchsorted(arr,[3,5,7])
print(n1)

[2 3 4]


***► NumPy Sorting Arrays***

In [ ]:
import numpy as np
n1 = np.array([1,3,8,0,6,77,-2])

print(np.sort(n1))

[-2  0  1  3  6  8 77]


In [ ]:
import numpy as np
n1 = np.array(['cat','boss', 'dog', 'apple'])

print(np.sort(n1))

['apple' 'boss' 'cat' 'dog']


***→ Sorting a 2-D Array***

In [ ]:
import numpy as np

arr = np.array([[3, 2, 14], [5, 0, 1]])

print(np.sort(arr))

[[ 2  3 14]
 [ 0  1  5]]
